# Generated by Django 2.1.1 on 2018-11-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askschools', '0002_auto_20181116_1143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='parents_remark',
            new_name='ParentsRemark',
        ),
        migrations.RenameModel(
            old_name='school_data',
            new_name='SchoolData',
        ),
        migrations.AlterField(
            model_name='schools',
            name='ADVANTAGE',
            field=models.TextField(blank=True, help_text='what do parents tend to benefit  by entrusting their children\n\tin your school not more than 1000 characters', max_length=1000),
        ),
    ]
