# Generated by Django 2.1.1 on 2018-11-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askschools', '0003_auto_20181119_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolData',
        ),
        migrations.AddField(
            model_name='schools',
            name='AWARDS',
            field=models.CharField(blank=True, help_text='kindly list the schools Awards', max_length=150),
        ),
        migrations.AddField(
            model_name='schools',
            name='CURRICULUM',
            field=models.CharField(choices=[('Bri', 'British'), ('Ame', 'American'), ('Bri & Ame', 'British American'), ('Ger', 'German'), ('Fre', 'French')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schools',
            name='DIRECTION',
            field=models.CharField(help_text='give a brief description to your school ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schools',
            name='EXTRA_CURRICULUM',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schools',
            name='WEBSITE',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
