# Generated by Django 2.1.1 on 2018-12-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askschools', '0005_auto_20181203_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club',
            field=models.CharField(choices=[('jet', 'Jet Club'), ('Science', 'Science Club'), ('Drama', 'Drama Club'), ('Art & Culture', 'Art & Culture Club'), ('Debate ', 'Debate Club'), ('Comedy', 'Comedy Club'), ('Math', 'Mathematic Club'), ('Literature', 'Literature Club'), ('Books', 'Books Club'), ('History', 'History Club'), ('Press', 'Press Information and Photography Club'), ('Adventure', 'Adventure Club'), ('Religious', 'Religious Club'), ('Charity', 'Charity Club'), ('Feeders', 'Feeders Club')], max_length=300),
        ),
        migrations.AlterField(
            model_name='gender',
            name='sex',
            field=models.CharField(choices=[('male', 'Male Only'), ('female', 'Female Only'), ('mixed', 'Mixed')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sports',
            name='sport',
            field=models.CharField(choices=[('Swimming Pool', 'Swimming '), ('BasketBall Court ', 'BasketBall'), ('FootBall Field', 'FootBall'), ('HandBall Court', 'HandBall'), ('VolleyBall Court', 'VolleyBall'), ('Race Track', 'Race'), ('Javelline', 'Javelline'), ('Short Put', 'Short Put'), ('Chess Board', 'Chess')], max_length=150),
        ),
    ]
