# Generated by Django 2.1.1 on 2018-12-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askschools', '0006_auto_20181203_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schools',
            old_name='ADDRESS',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='ADVANTAGE',
            new_name='Advantage',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='AWARDS',
            new_name='Awards',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='BADGE',
            new_name='Badge',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='CURRICULUM',
            new_name='Curriculum',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='DIRECTION',
            new_name='Direction',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='EMAIL',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='EXTRA_CURRICULUM',
            new_name='Extra_curriculum',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='extra_activities',
            new_name='Extra_curriculum_activities',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='FEES_RANGE',
            new_name='Fees_range',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='GENDER',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='LEVEL',
            new_name='Level',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='MOTTO',
            new_name='Motto',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='PHONE',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='SCHOOL_NAME',
            new_name='School_name',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='SCHOOL_TYPE',
            new_name='School_type',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='SPORTS',
            new_name='Sport_activities',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='STATE',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='TOWN',
            new_name='Town',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='VIDEO',
            new_name='Video',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='WEBSITE',
            new_name='Website',
        ),
    ]
